# For details, see https://github.com/devcontainers/images/tree/main/src/ruby
FROM mcr.microsoft.com/devcontainers/ruby:1-3.2-bullseye

COPY welcome-message.txt /usr/local/etc/vscode-dev-containers/first-run-notice.txt